name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: push images to registry
    runs-on: ubuntu-latest
    
    steps:
      - name: checkcode
        uses: actions/checkout@v4
      
      - name: build and push to Azure container registry
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.USER_NAME }}
         key: ${{ secrets.DEMO_KEY }}
         port: ${{ secrets.PORT }}
         script: |
          sudo su
          cd /home/azureuser/Demo &&
          sudo git pull
          docker tag firstimage contgs.azurecr.io/firstimage
          docker push contgs.azurecr.io/firstimage
          
          
         
         
         
          
          

      
      
        
