name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: push images to registry
    runs-on: ubuntu-latest
    
    steps:
      - name: checkcode
        uses: actions/checkout@v4
      
      - name: build and push to docker on ec2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.USER_NAME }}
         password: ${{ secrets.SSH_PASSWORD }}
         script: |
          sudo su
          cd /home/azureuser/Demo &&
          docker build -t nicimage .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag nicimage nikkoworld/nicimage:latest
          docker push nikkoworld/nicimage:latest
         
         
         
          
          

      
      
        
