name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: checkcode
        uses: actions/checkout@v4

      - name: deploy to ec2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.USER_NAME }}
         password: ${{ secrets.SSH_PASSWORD }}
         script: |
              sudo git config --global --add safe.directory /home/azureuser/Demo
              sudo cd /home/azureuser/Demo &&
              sudo git checkout main &&
              sudo git fetch --all &&
              sudo git reset --hard origin/main &&
              sudo git pull origin main &&
              sudo npm install
              sudo /root/.nvm/versions/node/v21.7.3/bin/pm2 start index.js --name "backend node" -- --port 7000
      
        
