name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: push images to registry
    runs-on: ubuntu-latest
    
    steps:
      - name: checkcode
        uses: actions/checkout@v4
      
      - name: build and push to docker on ec2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.USER_NAME }}
         key: ${{ secrets.DEMO_KEY }}
         port: ${{ secrets.PORT }}
         script: |
          sudo su
          cd /home/azureuser/Demo &&
          sudo docker build -t sampleguide:latest .
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker tag sampleguide:latest nikkoworld/sampleguide:latest
          sudo docker push nikkoworld/sampleguide:latest
          kubectl apply -f kube.yaml
          kubectl get deployment
          kubectl get svc
          kubectl get pods
         
         
         
          
          

      
      
        
